controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    # Example routes.yaml

show_admin:
    path: '/showadmin'
    controller: 'App\Controller\PersonneController::showAdmin'

    
